swagger: '2.0'
info:
  title: Documentation de l'API Bank Argent
  description: Contient tous les points d'accès API disponibles dans ce code.
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - Module Utilisateur
      summary: Connexion
      description: API pour la connexion d'un utilisateur.
      parameters:
        - in: body
          name: body
          description: Charge utile de connexion.
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Connexion réussie
          schema:
            $ref: '#/definitions/LoginResponse'
        '401':
          description: Utilisateur inconnu
        '402':
          description: Mot de passe erroné
        '500':
          description: Erreur interne du serveur

  /user/signup:
    post:
      tags:
        - Module Utilisateur
      summary: Inscription
      description: API pour l'inscription d'un utilisateur.
      parameters:
        - in: body
          name: body
          description: Charge utile d'inscription.
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Inscription réussie
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: API du profil utilisateur
      description: API pour récupérer le profil d'un utilisateur.
      responses:
        '200':
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

    put:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: API du profil utilisateur
      description: API pour mettre à jour le profil d'un utilisateur.
      parameters:
        - in: body
          name: body
          description: Attributs à mettre à jour du profil utilisateur.
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: Profil utilisateur mis à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

  /users/{userId}/transactions:
    get:
      summary: Récupérer toutes les transactions
      description: Récupère toutes les transactions pour l'utilisateur spécifié.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Paramètres invalides
        '401':
          description: Non autorisé, jeton invalide
        '500':
          description: Erreur interne du serveur

  /users/{userId}/transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction
      description: Récupère les détails d'une transaction spécifique.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/TransactionDetailResponse'
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

    post:
      summary: Créer une transaction
      description: Crée une nouvelle transaction pour l'utilisateur spécifié.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          description: Charge utile de création de transaction.
          required: true
          schema:
            $ref: '#/definitions/TransactionCreateRequest'
      security:
        - Bearer: []
      responses:
        '201':
          description: Transaction créée avec succès
          schema:
            $ref: '#/definitions/TransactionDetailResponse'
        '400':
          description: Données invalides
        '500':
          description: Erreur interne du serveur

    put:
      summary: Modifier une transaction
      description: Modifie une transaction existante.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          description: Charge utile de mise à jour de transaction.
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdateRequest'
      security:
        - Bearer: []
      responses:
        '200':
          description: Transaction mise à jour avec succès
          schema:
            $ref: '#/definitions/TransactionDetailResponse'
        '400':
          description: Données invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

    delete:
      summary: Supprimer une transaction
      description: Supprime une transaction existante.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '204':
          description: Transaction supprimée avec succès
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

  /categories:
    post:
      summary: Créer une catégorie
      description: Crée une nouvelle catégorie et une note associée.
      parameters:
        - in: body
          name: body
          description: Charge utile de création de catégorie.
          required: true
          schema:
            $ref: '#/definitions/CategoryCreateRequest'
      responses:
        '201':
          description: Catégorie créée avec succès
        '400':
          description: Données invalides
        '500':
          description: Erreur interne du serveur

  /categories/{categoryId}:
    put:
      summary: Modifier une catégorie
      description: Modifie une catégorie existante et une note associée.
      parameters:
        - name: categoryId
          in: path
          required: true
          type: string
        - in: body
          name: body
          description: Charge utile de mise à jour de catégorie.
          required: true
          schema:
            $ref: '#/definitions/CategoryUpdateRequest'
      responses:
        '200':
          description: Catégorie mise à jour avec succès
        '400':
          description: Données invalides
        '404':
          description: Catégorie non trouvée
        '500':
          description: Erreur interne du serveur

    delete:
      summary: Supprimer une catégorie
      description: Supprime une catégorie existante.
      parameters:
        - name: categoryId
          in: path
          required: true
          type: string
      responses:
        '204':
          description: Catégorie supprimée avec succès
        '404':
          description: Catégorie non trouvée
        '500':
          description: Erreur interne du serveur

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: Email de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur
      firstName:
        type: string
        description: Prénom de l'utilisateur
      lastName:
        type: string
        description: Nom de famille de l'utilisateur
      userName:
        type: string
        description: Nom public de l'utilisateur

  Login:
    properties:
      email:
        type: string
        description: Email de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur

  LoginResponse:
    properties:
      token:
        type: string
        description: Token JWT pour l'authentification

  UserProfile:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      userName:
        type: string

  ApiResponse:
    type: object
    properties:
      message:
        type: string
        description: Message retourné par l'API
      data:
        type: object

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: ID de la transaction
      userId:
        type: string
        description: ID de l'utilisateur
      amount:
        type: number
        format: float
        description: Montant de la transaction
      date:
        type: string
        format: date-time
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction

  TransactionDetailResponse:
    type: object
    properties:
      transaction:
        $ref: '#/definitions/Transaction'

  TransactionCreateRequest:
    type: object
    properties:
      amount:
        type: number
        format: float
        description: Montant de la transaction
      description:
        type: string
        description: Description de la transaction

  TransactionUpdateRequest:
    type: object
    properties:
      amount:
        type: number
        format: float
        description: Montant de la transaction
      description:
        type: string
        description: Description de la transaction

  CategoryCreateRequest:
    type: object
    properties:
      name:
        type: string
        description: Nom de la catégorie
      description:
        type: string
        description: Description de la catégorie

  CategoryUpdateRequest:
    type: object
    properties:
      name:
        type: string
        description: Nom de la catégorie
      description:
        type: string
        description: Description de la catégorie
