swagger: '2.0'
info:
  title: Documentation de l'API Bank Argent
  description: Contient tous les points d'accès API disponibles dans ce code.
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - Module Utilisateur
      summary: Connexion
      description: API pour la connexion d'un utilisateur.
      parameters:
        - in: body
          name: body
          description: Charge utile de connexion.
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Connexion réussie
          schema:
            $ref: '#/definitions/LoginResponse'
        '401':
          description: Utilisateur inconnu
        '402':
          description: Mot de passe erroné
        '500':
          description: Erreur interne du serveur

  /user/signup:
    post:
      tags:
        - Module Utilisateur
      summary: Inscription
      description: API pour l'inscription d'un utilisateur.
      parameters:
        - in: body
          name: body
          description: Charge utile d'inscription.
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Inscription réussie
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: API du profil utilisateur
      description: API pour récupérer le profil d'un utilisateur.
      responses:
        '200':
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

    put:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: API du profil utilisateur
      description: API pour mettre à jour le profil d'un utilisateur.
      parameters:
        - in: body
          name: body
          description: Attributs à mettre à jour du profil utilisateur.
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: Profil utilisateur mis à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

  /users/{userId}/transactions:
    get:
      tags:
        - Module Transactions
      summary: Récupérer toutes les transactions
      description: Récupère toutes les transactions pour l'utilisateur spécifié.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: ID unique de la transaction
                date:
                  type: string
                  format: date-time
                  description: Date de la transaction
                amount:
                  type: number
                  format: float
                  description: Montant de la transaction
                balance:
                  type: number
                  format: float
                  description: Solde après la transaction
        '400':
          description: Paramètres invalides
        '401':
          description: Non autorisé, jeton invalide
        '500':
          description: Erreur interne du serveur

  /users/{userId}/transactions/{transactionId}:
    get:
      tags:
        - Module Transactions
      summary: Récupérer une seule transaction
      description: Récupère les détails d'une transaction spécifique.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            type: object
            properties:
              id:
                type: integer
                description: ID unique de la transaction
              date:
                type: string
                format: date-time
                description: Date de la transaction
              amount:
                type: number
                format: float
                description: Montant de la transaction
              balance:
                type: number
                format: float
                description: Solde après la transaction
              transactionType:
                type: string
                description: Type de la transaction
              category:
                type: string
                example: "Default"
                description: Catégorie de la transaction
              note:
                type: string
                example: "Default"
                description: Note associée à la transaction
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

    put:
      tags:
        - Module Transactions
      summary: Modifier une transaction
      description: Modifie la catégorie et la note d'une transaction existante.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          description: Charge utile de mise à jour de la transaction.
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                description: Nouvelle catégorie de la transaction
              note:
                type: string
                description: Nouvelle note de la transaction
      security:
        - Bearer: []
      responses:
        '200':
          description: Transaction mise à jour avec succès
          schema:
            type: object
            properties:
              category:
                type: string
              note:
                type: string
        '400':
          description: Données invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: Email de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur
      firstName:
        type: string
        description: Prénom de l'utilisateur
      lastName:
        type: string
        description: Nom de famille de l'utilisateur
      userName:
        type: string
        description: Nom public de l'utilisateur

  Login:
    properties:
      email:
        type: string
        description: Email de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur

  LoginResponse:
    properties:
      token:
        type: string
        description: Token JWT pour l'authentification

  UserProfile:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      userName:
        type: string

  ApiResponse:
    type: object
    properties:
      message:
        type: string
        description: Message retourné par l'API
      data:
        type: object

