swagger: '2.0'
info:
  description: Documentation de l'API de Bank Argent
  version: 1.0.0
  title: Bank Argent API
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      summary: Connexion
      description: API pour la connexion
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Login'
      responses:
        '200':
          description: Connexion réussie
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /user/signup:
    post:
      summary: Inscription
      description: API pour l'inscription
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Inscription réussie
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /user/profile:
    get:
      summary: API de Profil Utilisateur
      description: API pour récupérer le profil d'un utilisateur
      responses:
        '200':
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
    put:
      summary: Mise à jour du profil utilisateur
      description: API pour mettre à jour le profil d'un utilisateur
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      responses:
        '200':
          description: Profil utilisateur mis à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /users/{userId}/transactions:
    get:
      summary: Récupérer les transactions d'un utilisateur
      description: Récupérer toutes les transactions pour le mois en cours, groupées par compte.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: Identifiant de l'utilisateur.
        - name: Authorization
          in: header
          required: true
          type: string
          description: Jeton d'authentification JWT.
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  type: object
                  properties:
                    accountId:
                      type: string
                      description: Identifiant du compte.
                    transactions:
                      type: array
                      items:
                        $ref: '#/definitions/Transaction'
        '400':
          description: Paramètres invalides
        '401':
          description: Non autorisé, jeton invalide
        '500':
          description: Erreur interne du serveur
  /users/{userId}/transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction
      description: Récupérer les détails d'une transaction spécifique.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: Identifiant de l'utilisateur.
        - name: transactionId
          in: path
          required: true
          type: string
          description: Identifiant de la transaction.
        - name: Authorization
          in: header
          required: true
          type: string
          description: Jeton d'authentification JWT.
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Transaction introuvable
        '500':
          description: Erreur interne du serveur
    put:
      summary: Mettre à jour une transaction
      description: Mettre à jour une transaction existante en modifiant uniquement la catégorie et la note.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: Identifiant de l'utilisateur.
        - name: transactionId
          in: path
          required: true
          type: string
          description: Identifiant de la transaction.
        - name: Authorization
          in: header
          required: true
          type: string
          description: Jeton d'authentification JWT.
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                example: "Alimentation"
              note:
                type: string
                example: "Achat au supermarché"
      responses:
        '200':
          description: Transaction mise à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Données d'entrée invalides
        '404':
          description: Transaction introuvable
        '500':
          description: Erreur interne du serveur
definitions:
  User:
    type: object
    properties:
      email:
        type: string
        description: Email de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur
      firstName:
        type: string
        description: Prénom de l'utilisateur
      lastName:
        type: string
        description: Nom de famille de l'utilisateur
      userName:
        type: string
        description: Nom public de l'utilisateur
  Login:
    type: object
    properties:
      email:
        type: string
        description: Email de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
        description: Nom public de l'utilisateur
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
        description: Identifiant de la transaction
      amount:
        type: number
        format: double
        description: Montant de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      category:
        type: string
        description: Catégorie de la transaction
      note:
        type: string
        description: Note sur la transaction
