swagger: '2.0'
info:
  description: Bank Argent API documentation
  version: 1.0.0
  title: Bank Argent API
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      summary: Login
      description: API for Login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Login Successfully
          schema:
            type: object
            properties:
              token:
                type: string
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      summary: Signup
      description: API for Signup
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              userName:
                type: string
      responses:
        '200':
          description: Signup Successfully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      summary: Update User Profile API
      description: API for updating a user profile
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              userName:
                type: string
      responses:
        '200':
          description: User profile updated successfully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /users/{userId}/transactions:
    get:
      summary: Retrieve User Transactions
      description: Retrieve all transactions for the current month, grouped by account.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: trans_001
                    amount:
                      type: number
                      format: double
                      example: 150
                    date:
                      type: string
                      format: date
                      example: '2024-10-05'
                    accountId:
                      type: string
                      example: acc_001
                    description:
                      type: string
                      example: Achat au magasin
                    status:
                      type: string
                      example: terminé
        '400':
          description: Invalid Parameters
        '401':
          description: Unauthorized, invalid token
        '500':
          description: Internal Server Error
  /users/{userId}/transactions/{transactionId}:
    get:
      summary: Retrieve Transaction Details
      description: Retrieve details of a specific transaction.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: object
                properties:
                  id:
                    type: string
                    example: trans_001
                  amount:
                    type: number
                    format: double
                    example: 150
                  date:
                    type: string
                    format: date
                    example: '2024-10-05'
                  accountId:
                    type: string
                    example: acc_001
                  description:
                    type: string
                    example: Achat au magasin
                  status:
                    type: string
                    example: terminé
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      summary: Update Transaction
      description: Update an existing transaction without deleting or adding a new one.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              amount:
                type: number
                format: double
                example: 150
              description:
                type: string
                example: Description mise à jour
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
        '400':
          description: Invalid input data
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
definitions:
  User:
    type: object
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
      firstName:
        type: string
        description: User first name
      lastName:
        type: string
        description: User last name
      userName:
        type: string
        description: User public name
  Login:
    type: object
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
        description: User public name
